# Generated by Django 3.1.7 on 2021-04-12 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='', max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('rightAnswer', models.CharField(max_length=255)),
                ('a1', models.CharField(max_length=255)),
                ('a2', models.CharField(max_length=255)),
                ('a3', models.CharField(max_length=255)),
                ('correctFeedback', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('incorrectFeedback', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
