# Generated by Django 3.2 on 2021-05-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Multiple Choice Question', 'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='answer_order',
            field=models.CharField(blank=True, choices=[('hold', 'hold'), ('random', 'Random')], help_text='The order in which multichoice                             answer options are displayed                             to the user', max_length=30, null=True, verbose_name='Answer Order'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Question'),
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
